# Site settings
title: Sources blog
description: "A place to get all new updates"
url: "https://starksources.github.io/blog/"
author:
  name: "Bharath Sathuri"
  email: "sathuribharathbrothers1234@gmail.com"
  url: "https://starksources.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
navigation-menu: false
